import { STR } from '../core/i18n';

// Extra UI strings (merged into the core table at module load).
Object.assign(STR, {
  tapStart: { de: 'TIPPEN ZUM STARTEN', en: 'TAP TO START' },
  worldTour: { de: 'WELTTOUR', en: 'WORLD TOUR' },
  cars: { de: 'AUTOS', en: 'CARS' },
  drive: { de: 'FAHREN', en: 'DRIVE' },
  stats: { de: 'WERTE', en: 'STATS' },
  unlocked: { de: 'FREIGESCHALTET!', en: 'UNLOCKED!' },
  needCoins: { de: 'ES FEHLEN {n} MÜNZEN', en: '{n} COINS MISSING' },
  toShop: { de: 'ZUM SHOP', en: 'GO TO SHOP' },
  revives: { de: 'REVIVES', en: 'REVIVES' },
  reviveBuy: { de: 'REVIVES KAUFEN', en: 'BUY REVIVES' },
  bestDeal: { de: 'BESTER DEAL', en: 'BEST DEAL' },
  bonus: { de: 'BONUS', en: 'BONUS' },
  processing: { de: 'WIRD GEKAUFT…', en: 'PROCESSING…' },
  purchased: { de: 'GEKAUFT!', en: 'PURCHASED!' },
  purchaseFailed: { de: 'KAUF FEHLGESCHLAGEN', en: 'PURCHASE FAILED' },
  restored: { de: '{n} KÄUFE WIEDERHERGESTELLT', en: '{n} PURCHASES RESTORED' },
  nothingRestored: { de: 'NICHTS WIEDERHERZUSTELLEN', en: 'NOTHING TO RESTORE' },
  legal: { de: 'KÄUFE SIND AN DEINE APPLE-ID GEBUNDEN', en: 'PURCHASES ARE TIED TO YOUR APPLE ID' },
  revivePack: { de: 'WEITERFAHREN', en: 'KEEP DRIVING' },
  coinPacks: { de: 'MÜNZEN', en: 'COINS' },
  bundles: { de: 'PAKETE', en: 'BUNDLES' },
  tankPack: { de: 'PANZER-PAKET', en: 'TANK PACK' },
  tankPackDesc: { de: 'LEOPARD 2 + WOLF APC SOFORT', en: 'LEOPARD 2 + WOLF APC NOW' },
  legendPass: { de: 'LEGENDEN-PASS', en: 'LEGEND PASS' },
  legendPassDesc: { de: 'DOPPELTE MÜNZEN + VOLT LINI', en: 'DOUBLE COINS + VOLT LINI' },
  unlockAll: { de: 'ALLES FREISCHALTEN', en: 'UNLOCK ALL' },
  unlockAllDesc: { de: 'ALLE 48 AUTOS SOFORT', en: 'ALL 48 CARS INSTANTLY' },
  lefty: { de: 'LINKSHÄNDER', en: 'LEFT-HANDED' },
  resetTutorial: { de: 'TUTORIAL ZURÜCKSETZEN', en: 'RESET TUTORIAL' },
  resetProgress: { de: 'FORTSCHRITT LÖSCHEN', en: 'ERASE PROGRESS' },
  resetSure: { de: 'WIRKLICH ALLES LÖSCHEN?', en: 'ERASE EVERYTHING?' },
  yes: { de: 'JA', en: 'YES' },
  no: { de: 'NEIN', en: 'NO' },
  auto: { de: 'AUTO', en: 'AUTO' },
  credits: { de: 'CARLANE · 48 AUTOS · 30 STÄDTE', en: 'CARLANE · 48 CARS · 30 CITIES' },
  newLabel: { de: 'NEU!', en: 'NEW!' },
  totalStars: { de: 'STERNE', en: 'STARS' },
  lanes: { de: 'SPUREN', en: 'LANES' },
  reward: { de: 'BELOHNUNG', en: 'REWARD' },
  nextLevel: { de: 'NÄCHSTES LEVEL', en: 'NEXT LEVEL' },
  retry: { de: 'NOCHMAL', en: 'RETRY' },
  toMap: { de: 'KARTE', en: 'MAP' },
  perfect: { de: 'PERFEKT!', en: 'PERFECT!' },
  swipeStep: { de: 'WISCHE ← →', en: 'SWIPE ← →' },
  swipeStepSub: { de: 'AUSWEICHEN', en: 'DODGE TRAFFIC' },
  boostStep: { de: 'HALTEN', en: 'HOLD' },
  boostStepSub: { de: 'FÜR BOOST', en: 'FOR BOOST' },
  abilityStep: { de: 'TIPPE HIER', en: 'TAP HERE' },
  abilityStepSub: { de: 'SPEZIAL!', en: 'SPECIAL!' },
  tutorialDone: { de: 'LOS GEHT\'S!', en: 'LET\'S GO!' },
  skip: { de: 'ÜBERSPRINGEN', en: 'SKIP' },
  understood: { de: 'VERSTANDEN', en: 'GOT IT' },
  newAbility: { de: 'NEUE FÄHIGKEIT', en: 'NEW ABILITY' },
  wrecks: { de: 'WRACKS', en: 'WRECKS' },
  reviveCta: { de: 'WEITERFAHREN ♥', en: 'KEEP DRIVING ♥' },
  soundOn: { de: 'AN', en: 'ON' },
  soundOff: { de: 'AUS', en: 'OFF' },
  locked2: { de: 'GESPERRT', en: 'LOCKED' },
  city: { de: 'STADT', en: 'CITY' },
});
export const STRINGS_READY = true;
