import type { AbilityDef, AbilityId, AbilityKind, LocalizedText } from '../core/types';
import { P } from '../core/Palette';

// ─────────────────────────────────────────────────────────────────────────────
// Catalog of ability definitions (UI metadata: name, one-line explanation, kind, timing, icon, HUD colour).
// Runtime implementations live in game/abilities/ and follow the behaviour spec in docs/AGENT_GUIDE.md; the
// cooldown/duration numbers here are the canonical values those implementations should mirror.
// Names are ALL CAPS (the pixel font is caps-only anyway) and ≤ 16 chars so they fit centred at scale 2.
// Descriptions are ONE short sentence that wraps to ≤ 3 lines on the ability card.
// ─────────────────────────────────────────────────────────────────────────────

// HUD colours not in the shared palette
const SEPIA = '#c8a060';
const ICE = '#a0f0ff';
const LILAC = '#b070f0';
const EMBER = '#ff5030';

const def = (
  id: AbilityId, kind: AbilityKind, cooldown: number, duration: number | undefined, color: string,
  de: string, en: string, descDe: string, descEn: string,
): AbilityDef => {
  const name: LocalizedText = { de, en };
  const desc: LocalizedText = { de: descDe, en: descEn };
  const d: AbilityDef = { id, name, desc, kind, cooldown, icon: id, color };
  if (duration !== undefined) d.duration = duration;
  return d;
};

export const ABILITIES: Record<AbilityId, AbilityDef> = {
  // ── overdrive / movement ─────────────────────────────────────────────────
  nitro: def('nitro', 'duration', 9, 3, P.cyan,
    'GODZILLA-NITRO', 'GODZILLA NITRO',
    '3 Sekunden blauer Feuerstoß: Autos zerplatzen beim Rammen, du bleibst heil.',
    '3 seconds of blue fire: rammed cars burst, you take no damage.'),
  jump: def('jump', 'instant', 4.5, 1, P.white,
    'TOFU-HOP', 'TOFU HOP',
    'Springt in hohem Bogen über das nächste Auto.',
    'Leaps in a high arc over the next car.'),
  hop: def('hop', 'instant', 3, 0.5, P.yellowLight,
    'HASEN-HOP', 'BUNNY HOP',
    'Kurzer Hüpfer über ein Auto, fast ohne Abklingzeit.',
    'A short hop over one car, almost no cooldown.'),
  rocketjump: def('rocketjump', 'instant', 7, 1.5, P.orange,
    'RAKETEN-SPRUNG', 'ROCKET JUMP',
    'Raketen-Sprung: Die Landung zerstört alle Autos im Umkreis von 10 m.',
    'Rocket-powered jump: the landing wipes out every car within 10 m.'),
  wings: def('wings', 'duration', 9, 3, P.red,
    'EVO-FLÜGEL', 'EVO WINGS',
    'Der Flügel klappt aus: 3 Sekunden Flug über dem Verkehr.',
    'The wing unfolds: 3 seconds of flight above the traffic.'),
  blink: def('blink', 'instant', 6, undefined, P.cyan,
    'BLINK-SPRUNG', 'BLINK',
    'Teleport 60 m nach vorn. Wer dort steht, explodiert.',
    'Teleports 60 m ahead. Anything parked there explodes.'),
  phase: def('phase', 'duration', 8, 2.5, LILAC,
    'DRIFT-GEIST', 'DRIFT GHOST',
    '2,5 Sekunden Geisterform: Du fährst durch alle Autos hindurch.',
    '2.5 seconds of ghost form: you drive straight through every car.'),
  turbojet: def('turbojet', 'duration', 12, 4, P.blueLight,
    'TURBO-JET', 'TURBOJET',
    '4 Sekunden Jet-Modus: Tempo ×1,8, unverwundbar, alles wird zerquetscht.',
    '4 seconds of jet mode: speed ×1.8, invulnerable, everything gets crushed.'),
  ram: def('ram', 'duration', 6, 1.5, P.orange,
    'RAMMBOCK', 'RAM CHARGE',
    '1,5 Sekunden Eisen-Sturmlauf: Tempo ×1,4 und alles vor dir fliegt weg.',
    '1.5 seconds of iron charge: speed ×1.4 and everything ahead gets flattened.'),
  smokescreen: def('smokescreen', 'duration', 9, 4, P.gray1,
    'REIFENQUALM', 'SMOKE SCREEN',
    '4 Sekunden Drift-Qualm: unverwundbar, jeder Treffer zerlegt das Auto.',
    '4 seconds of drift smoke: invulnerable, every hit wrecks the other car.'),
  spin: def('spin', 'duration', 5, 1, P.yellow,
    'DRIFT-WIRBEL', 'DRIFT SPIN',
    'Eine Sekunde Pirouette: Autos in deiner und den Nachbarspuren fliegen weg.',
    'One-second pirouette: cars in your lane and the next lanes go flying.'),
  tornado: def('tornado', 'duration', 8, 3, P.teal,
    'DRIFT-TORNADO', 'DRIFT TORNADO',
    '3 Sekunden Wirbelsturm ums Auto: Nachbarspuren werden leergefegt.',
    '3-second tornado around the car: neighbouring lanes get swept clean.'),

  // ── size & armour ────────────────────────────────────────────────────────
  shrink: def('shrink', 'duration', 9, 4, P.pinkLight,
    'KEI-MODUS', 'KEI MODE',
    '4 Sekunden Winzling: halb so groß und du schlüpfst durch jede Lücke.',
    '4 seconds of tiny mode: half size, slipping through every gap.'),
  mega: def('mega', 'duration', 12, 5, P.red,
    'MEGA-MODUS', 'MEGA MODE',
    '5 Sekunden Riesen-Truck: Alles unter den Rädern wird plattgewalzt.',
    '5 seconds of giant truck: everything under the wheels gets flattened.'),
  shield: def('shield', 'duration', 12, 8, P.blueLight,
    'VIP-SCHILD', 'VIP SHIELD',
    '8 Sekunden Schutzblase, die zwei Treffer schluckt.',
    'An 8-second bubble that soaks up two hits.'),
  ironbumper: def('ironbumper', 'duration', 10, 6, P.gray1,
    'STAHL-BUMPER', 'IRON BUMPER',
    '6 Sekunden Rammschutz: Kollisionen zerstören Autos, ohne dir zu schaden.',
    '6 seconds of bull bar: collisions wreck cars without hurting you.'),
  repair: def('repair', 'instant', 12, undefined, P.green,
    'BOXENSTOPP', 'PIT STOP',
    'Sofort +2 Lebenspunkte mit Schraubenschlüssel-Funken.',
    'Instantly restores 2 hit points in a shower of wrench sparks.'),

  // ── shots & projectiles ──────────────────────────────────────────────────
  cannon: def('cannon', 'projectile', 2.5, undefined, P.orange,
    'DONNER-KANONE', 'THUNDER CANNON',
    'Feuert eine Granate die Spur hinunter und sprengt das erste Auto.',
    'Fires a shell down the lane and blows up the first car it meets.'),
  missile: def('missile', 'projectile', 5, undefined, EMBER,
    'ZIEL-RAKETE', 'HOMING MISSILE',
    'Lenkrakete, die das nächste Auto in jeder Spur jagt.',
    'A homing missile that chases the nearest car in any lane.'),
  laser: def('laser', 'instant', 8, 0.6, P.red,
    'WANGAN-LASER', 'WANGAN LASER',
    'Roter Laserstrahl die Spur hinunter: alles auf 120 m verdampft.',
    'A red laser beam down the lane: everything within 120 m evaporates.'),
  railgun: def('railgun', 'instant', 9, 0.8, ICE,
    'RAILGUN', 'RAILGUN',
    'Kurz aufladen, dann verschwindet alles in deiner Spur auf 200 m.',
    'Charge briefly, then everything in your lane within 200 m is gone.'),
  gatling: def('gatling', 'duration', 7, 3, P.yellow,
    'GATLING-FEUER', 'GATLING FIRE',
    '3 Sekunden Kugelhagel geradeaus durch deine Spur.',
    '3 seconds of bullet hail straight down your lane.'),
  plasma: def('plasma', 'projectile', 4, undefined, P.cyan,
    'PLASMA-TRIO', 'PLASMA TRI-SHOT',
    'Drei Plasmakugeln auf einmal: deine Spur und beide Nachbarspuren.',
    'Three plasma balls at once: your lane and both neighbours.'),
  shuriken: def('shuriken', 'projectile', 4, undefined, P.white,
    'SHURIKEN-WURF', 'SHURIKEN',
    'Wirft drei Wurfsterne in deine und die Nachbarspuren.',
    'Throws three ninja stars into your lane and the next ones.'),
  boulder: def('boulder', 'projectile', 6, undefined, P.tan,
    'FELS-LAWINE', 'BOULDER TOSS',
    'Drei hüpfende Felsbrocken rollen voraus, jeder Aufprall zerlegt ein Auto.',
    'Three bouncing boulders roll ahead, every bounce wrecks a car.'),
  mines: def('mines', 'projectile', 6, undefined, EMBER,
    'MINEN-WURF', 'MINE DROP',
    'Wirft drei Minen 30 m voraus in die anderen Spuren.',
    'Tosses three mines 30 m ahead into the other lanes.'),
  anchor: def('anchor', 'projectile', 5, undefined, P.gray1,
    'ANKER-WURF', 'ANCHOR TOSS',
    'Ein schwerer Anker pflügt 60 m durch deine Spur und alles darin.',
    'A heavy anchor ploughs 60 m down your lane and through everything in it.'),
  chain: def('chain', 'projectile', 4, undefined, P.gray1,
    'HARPUNEN-KETTE', 'HARPOON CHAIN',
    'Harpune packt das nächste Auto und reißt es von der Straße.',
    'A harpoon grabs the next car and yanks it off the road.'),
  fireworks: def('fireworks', 'projectile', 9, undefined, P.pinkLight,
    'FEUERWERK', 'FIREWORKS',
    'Raketen regnen auf alle Spuren 60 m voraus nieder.',
    'Rockets rain down on every lane within 60 m ahead.'),
  drone: def('drone', 'duration', 11, 5, P.red,
    'NSX-DROHNE', 'NSX DRONE',
    '5 Sekunden Kampfdrohne, die voraus alle Autos beschießt.',
    'A combat drone hovers ahead for 5 seconds, shooting every car.'),
  dragon: def('dragon', 'duration', 11, 2, P.gold,
    'NEON-DRACHE', 'NEON DRAGON',
    'Ein Pixel-Drache fliegt 2 Sekunden deine Spur hinab und verbrennt alles.',
    'A pixel dragon flies down your lane for 2 seconds, burning everything.'),

  // ── area blasts ──────────────────────────────────────────────────────────
  flame: def('flame', 'duration', 7, 2, P.orange,
    'VTEC-FLAMME', 'VTEC FLAME',
    '2 Sekunden Flammenwerfer: Autos bis 40 m vor dir gehen in Flammen auf.',
    '2 seconds of flamethrower: cars up to 40 m ahead go up in flames.'),
  emp: def('emp', 'duration', 10, 1, P.purple,
    'EMP-PULS', 'EMP PULSE',
    'Elektrischer Ring: Alle Autos im Umkreis von 80 m werden gegrillt.',
    'Electric ring: every car within 80 m gets fried and knocked aside.'),
  sonicboom: def('sonicboom', 'instant', 7, undefined, P.purple,
    'ÜBERSCHALL-KNALL', 'SONIC BOOM',
    'Ein Knall, alle Spuren: Autos im Umkreis von 25 m zerbersten.',
    'One bang, all lanes: cars within 25 m burst apart.'),
  shockwave: def('shockwave', 'instant', 7, undefined, P.blueLight,
    'SCHOCKWELLE', 'SHOCKWAVE',
    'Druckwelle: 15 m Umkreis wird zerstört, alles andere weggeschoben.',
    'Pressure wave: everything within 15 m is destroyed, the rest shoved away.'),
  quake: def('quake', 'instant', 9, undefined, P.brown,
    'BODEN-BEBEN', 'GROUND QUAKE',
    'Bodenschlag: Autos im Umkreis von 30 m fliegen in die Luft.',
    'Ground pound: cars within 30 m are launched into the air.'),
  lightning: def('lightning', 'instant', 7, undefined, P.yellowLight,
    'KETTENBLITZ', 'CHAIN LIGHTNING',
    'Ein Blitz springt auf bis zu vier Autos in der Nähe über.',
    'A bolt jumps across up to four nearby cars.'),
  bass: def('bass', 'instant', 8, undefined, P.pink,
    'BASS-DROP', 'BASS DROP',
    'Der Bass fällt: Autos im Umkreis von 20 m werden nach außen geschleudert.',
    'The bass drops: cars within 20 m get thrown outward.'),
  freeze: def('freeze', 'instant', 8, undefined, ICE,
    'EIS-STRAHL', 'ICE BEAM',
    'Eisstrahl 50 m voraus: eingefrorene Autos zersplittern harmlos.',
    'An ice beam 50 m ahead: frozen cars shatter harmlessly on contact.'),
  watercannon: def('watercannon', 'duration', 7, 2, P.cyan,
    'WASSERWERFER', 'WATER CANNON',
    '2 Sekunden Wasserstrahl, der Autos von der Straße spült.',
    '2 seconds of water jet washing cars right off the road.'),
  blossom: def('blossom', 'duration', 9, 4, P.sakura,
    'SAKURA-STURM', 'SAKURA STORM',
    '4 Sekunden Blütensturm, der Autos sanft von der Straße weht.',
    'A 4-second petal storm that gently blows cars off the road.'),

  // ── crowd control ────────────────────────────────────────────────────────
  horn: def('horn', 'instant', 5, undefined, P.yellow,
    'MEGA-HUPE', 'AIR HORN',
    'Schallwelle: Autos bis 40 m weichen in die Nachbarspuren aus.',
    'Sound wave: cars up to 40 m ahead scatter into the next lanes.'),
  lanerip: def('lanerip', 'instant', 6, undefined, P.orange,
    'SPUR-SCHUB', 'LANE RIP',
    'Alles in deiner Spur auf 100 m wird zur Seite geschoben.',
    'Everything in your lane within 100 m gets shoved aside.'),
  siren: def('siren', 'duration', 10, 5, P.blue,
    'POLIZEI-SIRENE', 'POLICE SIREN',
    '5 Sekunden Blaulicht: Der Verkehr voraus macht dir Platz.',
    '5 seconds of blue lights: traffic ahead pulls out of your way.'),
  magnet: def('magnet', 'duration', 10, 6, P.gold,
    'MÜNZ-MAGNET', 'COIN MAGNET',
    '6 Sekunden: Münzen aus allen Spuren fliegen zu dir.',
    '6 seconds: coins from every lane fly straight to you.'),
  goldrush: def('goldrush', 'duration', 12, 8, P.gold,
    'GOLDRAUSCH', 'GOLD RUSH',
    '8 Sekunden Goldaura: dreifache Münzen und Münzreihen in deiner Spur.',
    '8 seconds of gold aura: triple coins and coin rows in your lane.'),

  // ── time ─────────────────────────────────────────────────────────────────
  slowmo: def('slowmo', 'duration', 10, 3, ICE,
    'ZEITLUPE', 'SLOW-MO',
    '3 Sekunden Zeitlupe: Die Welt kriecht, du nicht.',
    '3 seconds of slow motion: the world crawls, you do not.'),
  timewarp: def('timewarp', 'duration', 10, 2, SEPIA,
    'ZEIT-STOPP', 'TIME WARP',
    '2 Sekunden Sepia-Stillstand: Der Verkehr friert ein, du fährst hindurch.',
    '2 seconds of sepia freeze: traffic stops dead, you drive right through.'),
};

export function getAbilityDef(id: AbilityId): AbilityDef {
  return ABILITIES[id] ?? ABILITIES.nitro;
}
